# Docker Compose 配置文件版本
version: '3.8'

# 定义所有服务
services:
  # 数据库服务 (MySQL)
  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    # 环境变量，用于配置MySQL
    environment:
      # 这是数据库的最高权限 (root) 密码
      MYSQL_ROOT_PASSWORD: 'jiangjin1010+'
      # 这是为WordPress创建的专用数据库的名称
      MYSQL_DATABASE: 'stack'
      # 这是为WordPress创建的专用数据库用户名 (已修正为全小写)
      MYSQL_USER: 'jcole'
      # 这是上面 'jcole' 用户的专用密码
      MYSQL_PASSWORD: 'jiangjin1010+' # <--- 【重要】请替换为您自己的密码
    # 数据卷，将数据库文件持久化到主机上
    volumes:
      - db_data:/var/lib/mysql
    # 网络设置
    networks:
      - wordpress_net

  # WordPress 服务
  wordpress:
    # 依赖于db服务，确保数据库先启动
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    # 端口映射：将主机的 542 端口映射到容器的 80 端口
    ports:
      - "542:80"
    # 环境变量，用于配置WordPress
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      # 以下三项必须与上面 db 服务中的设置保持一致
      WORDPRESS_DB_USER: 'jcole'
      WORDPRESS_DB_PASSWORD: 'jiangjin1010+' # <--- 【重要】请确保这里的密码和上面一致
      WORDPRESS_DB_NAME: 'stack'
      # 网站地址配置，确保后台样式正常
      WORDPRESS_SITEURL: "https://stack.wiitwo.eu.org"
      WORDPRESS_HOME: "https://stack.wiitwo.eu.org"
    # 数据卷，将WordPress核心文件、插件、主题持久化到主机上
    volumes:
      - ./wordpress_files:/var/www/html
    # 网络设置
    networks:
      - wordpress_net

# 定义数据卷
volumes:
  db_data:
  wordpress_files:

# 定义网络
networks:
  wordpress_net: